sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t allanjales-aja/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true allanjales-aja/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-613941455763"
  bucket_path: "docker"
  on:
   branch: master
